export const contactForm = [
	{
		tagType: 'regular',
		label: 'First Name',
		id: 'firstName',
		name: 'firstName',
		type: 'text',
		placeholder: 'First Name',
	},
	{
		tagType: 'regular',
		label: 'Last Name',
		id: 'lastName',
		name: 'lastName',
		type: 'text',
		placeholder: 'Last Name',
	},
	{
		tagType: 'regular',
		label: 'Middle Name',
		id: 'middleName',
		name: 'middleName',
		type: 'text',
		placeholder: 'Middle Name',
	},
	{
		tagType: 'regular',
		label: 'Country',
		id: 'country',
		name: 'country',
		type: 'text',
		placeholder: 'Country',
	},
	{
		tagType: 'regular',
		label: 'City',
		id: 'city',
		name: 'city',
		type: 'text',
		placeholder: 'City',
	},
	{
		tagType: 'regular',
		label: 'Street',
		id: 'street',
		name: 'street',
		type: 'text',
		placeholder: 'Street',
	},
	{
		tagType: 'regular',
		label: 'House',
		id: 'house',
		name: 'house',
		type: 'text',
		placeholder: 'House',
	},
	{
		tagType: 'regular',
		label: 'Flat',
		id: 'flat',
		name: 'flat',
		type: 'text',
		placeholder: 'Flat',
	},
	{
		tagType: 'regular',
		label: 'Email',
		id: 'email',
		name: 'email',
		type: 'text',
		placeholder: 'Email',
	},
	{
		tagType: 'masked',
		label: 'Phone number',
		id: 'telephone',
		name: 'telephone',
		type: 'text',
		format: '+380#########',
		mask: '#',
		placeholder: 'Phone number',
	},
];
