export * from './About';
export * from './Authorization';
export * from './Catalog';
export * from './Contacts';
export * from './Delivery';
export * from './Home';
export * from './Order';
export * from './PageNotFound';
export * from './Basket';
